### ISSUE TITLE
Set up automated integration testing

### ISSUE THREAD

**Issue by clausherther** [calogica/dbt-expectations#1]
We should set up Github Actions or something similar to allow us to kick off integration tests. This could be triggered to avoid BigQuery charges, or automated (at least for Postgres)

**Comment by nysthee** [comment]
I would like to work on this!

**Comment by sgoley** [comment]
Hey, github explorer & dbt fan here. 

I know what Dylan Baker over at [Spectacles ](http://spectacles.dev/) did was for bigquery column / schema tests was to run queries with `limit 0` appended. Basically, the query would succeed but return no data. 

I think this could be used for your schema expectation tests without incurring charges?

**Comment by makotonium** [comment]
@clausherther I am curious to see how this is coming, and I may be able to offer help on getting something set up. How are you currently testing locally? Maybe we could replicate that as a start on GitHub Actions.

**Comment by clausherther** [comment]
Hi @makotonium ! I haven't made ~much~ any progress here, since it hasn't been a blocker for development (yet). So far, I'm testing against my own BigQuery and Snowflake instances (in addition to a local postgres instance) which hasn't incurred any costs yet. I think your other note on documentation updates is probably much more impactful to the broader package user community, so if you had to chose a project, that's the one I'd direct the most energy to! :)
