### ISSUE TITLE
clarification on the use of expect_table_columns_to_match_set

### ISSUE THREAD

**Issue by s-vinay** [calogica/dbt-expectations#100]
Data warehouse: Bigquery

The test "expect_table_columns_to_match_set" is comparing the columns list provided in the "column_list" parameter with the columns in the model. When we have some additional column in the list which does not exist in the model the test is still successful.

This design misguides developers / testers in one particular scenario outlined below.
- developer has missed to add one or more column(s), which was required as per requirement, into a model
- as per the requirement, the test set included this column(s) which was missed by the developer
- now when the test is executed, the test does not fail as all other columns in the set exist in the model

Ideally, the test should compare every column provided in the parameter and even if one is missing it should fail. The table column count test will reveal the count differences but this test also should cover this scenario. Thoughts ?

**Comment by clausherther** [comment]
Hi @s-vinay, thanks for raising this issue! This makes sense, the current test is pretty rudimentary and just comparing columns counts. Definitely something we could improve! Is this something you're interested in working on?

**Comment by s-vinay** [comment]
Hello @clausherther, Thanks for the quick comment and I am really surprised how quick you respond to the issues along with your other daily routines.

I can give this a try, I am new to open source contribution and also probably just few weeks old using DBT but not new for SQL.
So, this comes with some challenges but am interested to start this and will come back soon.

Thanks,
Vinay

**Comment by clausherther** [comment]
@s-vinay no worries! If you'd like to contribute, happy to help! But if it's a bit much to start off with, also happy to take this on next week.

**Comment by s-vinay** [comment]
@clausherther, I have tried some changes - please review and your comments will be helpful
