### ISSUE TITLE
Package is out of date on dbt hub

### ISSUE THREAD

**Issue by mirosval** [calogica/dbt-expectations#105]
I know this issue does not belong here, but it seems that the `0.4.1` version, while released, has not been updated on the dbt hub which still shows `0.4.0`. I have created an issue there: https://github.com/dbt-labs/hub.getdbt.com/issues/755 but nobody responded. Would you know who to contact about fixing this?

**Comment by clausherther** [comment]
@mirosval sounds like there's a bug on package hub and they're working on it, see: https://getdbt.slack.com/archives/CU4MRJ7QB/p1627277595103500

**Comment by mirosval** [comment]
This has now been fixed
