### ISSUE TITLE
Not compatible with new version of dbt 0.21.0

### ISSUE THREAD

**Issue by Charles1104** [calogica/dbt-expectations#114]
I got an error when trying upgrading to new dbt version 0.21.0 with this package. It still doesn't support dbt 0.21.0.

**Comment by clausherther** [comment]
hi @Charles1104, 0.21 was just released, we'll be bumping up dbt-expectations this week (as soon as dbt-date is up-to-date on dbt package hub). Thanks for your patience.

**Comment by Charles1104** [comment]
Sure, no problem. Just wanted to give heads-up on compatibility issues. No rush ;)
