### ISSUE TITLE
Hardcode value in expect_column_to_exist.sql prevent functionality

### ISSUE THREAD

**Issue by UselessAlias** [calogica/dbt-expectations#117]
In this test there is an available parameter, transform, however the test value is hardcoded to have the upper filter applied on line 4. As the default value for the transform parameter is also upper the default state of the function works fine. However, if any other filters are passed through the transform parameter then the test will most likely fail. For example any test which passes the transform value "lower" is guaranteed to fail as it will only lower the column list and not the test column name. 

Doesn't really cause any major issues, but thought it was worth flagging.

This is the quick fix I've implemented in my repo for line 4:
    {%- set column_name = column_name | map(transform) | join -%}

**Comment by clausherther** [comment]
Good [find](https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/table_shape/expect_column_to_exist.sql#L4)!

Did you want to submit a PR for this? I can do this, but didn't want to get ahead of you if you wanted to do that. Either way, thanks for flagging!
