### ISSUE TITLE
reference a view and not a table

### ISSUE THREAD

**Issue by misteliy** [calogica/dbt-expectations#12]
Hi,

I wanted to reference a view:

models:
  - name: my_table
    description: This table contains our toy model
    tests:
      - dbt_expectations.expect_table_column_count_to_equal_other_table:
          compare_model: ref("my_table_view")

resulting in:

Failure in test dbt_expectations_expect_table_column_count_to_equal_other_table_my_table_ref_my_table_view_ (models/my_first_folder/schema.yml)
  Got 7 results, expected 0.

are the tests only working with tables?

**Comment by clausherther** [comment]
Hey @misteliy sorry just saw this, somehow I didn't set up GH notifications correctly.

No, there's no reason the tests shouldn't work with views, in fact my initial integration tests were using views. Any chance this is an underlying data problem? Which platform (BG, Snowflake..) are you on?

I'll check this out locally, but please let me know if you're still seeing this.

**Comment by clausherther** [comment]
Confirmed this works on BQ and Snowflake:

- Created a view that selects from test table
`data_test_view.sql`
```sql
{{
    config(
    materialized = 'view'
    )
}}

select * from {{ ref('data_test') }}
```

Confirmed that test works in both directions:
```sql
  - name: data_test_view
    tests:
        - dbt_expectations.expect_table_column_count_to_equal_other_table:
            compare_model: ref("data_test")

  - name: data_test
    tests:
        - dbt_expectations.expect_table_column_count_to_equal_other_table:
            compare_model: ref("data_test_view")
```

**Comment by clausherther** [comment]
Closing this, but feel free to reopen if you're still having this issue. Thanks!
