### ISSUE TITLE
Update docs with expect_table_columns_to_contain_set example

### ISSUE THREAD

**Issue by epapineau** [calogica/dbt-expectations#120]
There is no example in the readme for the expect_table_columns_to_contain_set test and [the hyperlink](https://github.com/calogica/dbt-expectations#expect_table_columns_to_contain_set) is broken.

**Comment by epapineau** [comment]
Absolutely~ Just submitted one @clausherther

**Comment by clausherther** [comment]
Closed via #121 👏
