### ISSUE TITLE
Regression in expect_table_columns_to_match_ordered_list

### ISSUE THREAD

**Issue by mirosval** [calogica/dbt-expectations#122]
Hello, this appears to have regressed in dbt `0.21.0` and dbt_expectations `0.4.4`. It looks like it happened here: https://github.com/calogica/dbt-expectations/commit/c698a1a1108435c18cc7680885795aeb47b8fe74#diff-14b201719d47d2b58e18a4896f8cb1d1f0bc3b414694499ef5eb738b683fb955L11-L12

It was fixed in #99

**Comment by clausherther** [comment]
Hi @mirosval ! Could you describe what error you're seeing and what platform you're on? The PR you reference that fixed  #99 (which was PR [#101](https://github.com/calogica/dbt-expectations/pull/101/files)) used the old way of deriving the missing columns. We changed this to a join based approach that doesn't rely on this type casting to `varchar` anymore.

**Comment by mirosval** [comment]
Thanks for looking into this!

The error is the same, `failed to find conversion function from "unknown" to text`

The rendered SQL is:
```
select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
      with relation_columns as (
        select
            1 as relation_column_idx,
            'DIM_DATE' as relation_column               <---- HERE
    ),
    input_columns as (
        select
            1 as input_column_idx,
            'DIM_DATE' as input_column                  <---- HERE
    )
    select *
    from
        relation_columns r
        full outer join
        input_columns i on r.relation_column = i.input_column and r.relation_column_idx = i.input_column_idx
    where
        -- catch any column in input list that is not in the sequence of table columns
        -- or any table column that is not in the input sequence
        r.relation_column is null or
        i.input_column is null
    ) dbt_internal_test
```

When I run this SQL in Redshift it fails with the above error, when I add `::text` to the places pointed out in the snippet, it works.

As far as I can tell, this code corresponds to what is currently on master.

**Comment by clausherther** [comment]
Got it, thanks! I'll try and get to this in the next couple of days, unless you want to beat me to it with a PR ;)
