### ISSUE TITLE
Redundant set definition + Feature request in `expect_multiculumn_sum_to_equal`

### ISSUE THREAD

**Issue by Gregory108** [calogica/dbt-expectations#129]
https://github.com/calogica/dbt-expectations/blob/d7f98601811db2532510a70103f66f9784bc979c/macros/schema_tests/multi-column/expect_multicolumn_sum_to_equal.sql#L9

Why would we need this set that is not used?

Also, is it possible to implement this test:
- to be equal to another variable
- or have coefficients near variables
- and have an option to `COALESCE` variables if not all of them are `NULL`? Or not sum if any of them is `NULL`?

**Comment by clausherther** [comment]
hi @Gregory108, thanks for bringing this up, that `operator` is a copy & paste issue, easy fix. 

If you'd like to add new tests to the repo, feel free to submit a PR (or a more specific issue if you'd like more feedback first)! 👍
