### ISSUE TITLE
Inaccurate Documentation for expect_column_distinct_values_to_[be_in/contain/equal]_set

### ISSUE THREAD

**Issue by kdw2126** [calogica/dbt-expectations#133]
The documentation in the README.md file list "group_by" as a possible argument for these three tests:

- expect_column_distinct_values_to_be_in_set
- expect_column_distinct_values_to_contain_set
- expect_column_distinct_values_to_equal_set

However, I just got an error when I tried adding a group_by to one of these tests, and examining the source code reveals that none of these three tests accept "group_by" as an argument.  

I would submit a PR to fix but I wasn't sure whether the issue was the documentation or that these tests are missing group_by as a feature.

**Comment by clausherther** [comment]
Hey @kdw2126 ! Thanks for raising this issue. Looks like that's just a bug in the docs, the actual test doesn't have these params at all.
For example: https://github.com/calogica/dbt-expectations/blob/75bb33560788159af10bd5d35dc5b027f224b9ba/macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_be_in_set.sql#L1

If you have the time, a PR to the README would be great, but I can get to this next week for sure.

**Comment by clausherther** [comment]
Btw, I don't think a `group by` would even make sense here, I can't think of a use case where that would work. If you can think of one though, happy to discuss!

**Comment by kdw2126** [comment]
@clausherther Thanks for the quick response and happy New Year!  And yes, what I was trying to do was nonsensical but now the documentation won't lead anyone else down the same trap!
