### ISSUE TITLE
Number out of representable range

### ISSUE THREAD

**Issue by eric3kim** [calogica/dbt-expectations#16]
Error: 100046 (22003): Number out of representable range: type FIXED[SB16](38,12)
The error is occurring due to below error in Snowflake. 
https://community.snowflake.com/s/article/Number-out-of-representable-range-error-occurs-during-the-multiplication-of-numeric-values

**Comment by clausherther** [comment]
Hi @eric3kim which test is causing this error? Also could you please add any more context so I can try to reproduce this?

**Comment by eric3kim** [comment]
Apologies, should've been a little more helpful. I am doing expect_column_values_to_be_within_n_moving_stdevs and expect_column_values_to_be_within_n_stdevs on more than billions of rows with column NUMBER(19,4).

**Comment by clausherther** [comment]
I think the full test yaml specification would help, although I suspect this is largely a factor of your actual data. These two tests happen to not yet `row_condition` implemented and I'm not sure how to best incorporate a filter in this case. Happy to accept PRs though if you have any suggestions.

**Comment by clausherther** [comment]
@eric3kim closing this, feel free to reopen if you have a bit info on how you're using this test. Thanks!
