### ISSUE TITLE
Documentation for expect_column_values_to_be_between is incorrect

### ISSUE THREAD

**Issue by dougscc** [calogica/dbt-expectations#167]
# Error
`macro 'dbt_macro__test_expect_column_values_to_be_between' takes no keyword argument 'minimum'`

# Docs say

[expect_column_values_to_be_between](https://github.com/calogica/dbt-expectations/tree/0.5.5/macros/schema_tests/column_values_basic/expect_column_values_to_be_between.sql)
Expect each column value to be between two values.

tests:
  - dbt_expectations.expect_column_values_to_be_between:
      minimum: 0
      maximum: 10

# Actual Args

Expects `min_value` and `max_value`
```
        - dbt_expectations.expect_column_values_to_be_between:
            min_value: 200701
            max_value: 202504
```

**Comment by clausherther** [comment]
Hi @dougscc! Not sure where you saw that in the docs, but here's a screenshot of our current docs where the correct parameters are shown: 
<img width="885" alt="image" src="https://user-images.githubusercontent.com/7342749/163898425-4e226117-8644-4a6e-81f6-059d036da044.png">

Please feel free to reopen if you see something else wrong with this test's docs.
