### ISSUE TITLE
expect_column_values_to_be_between unexpected behavior

### ISSUE THREAD

**Issue by tcwou** [calogica/dbt-expectations#17]
expect_column_values_to_be_between should use the "and" operator instead of "or"

```
{% set expression %}
{{ column_name ~ " >= " ~ min_value ~ " or " ~
   column_name ~ " <= " ~ max_value }}
{% endset %}
```

**Comment by clausherther** [comment]
Whoa! Leftover from a previous implementation. Thanks for finding this. Should be a quick fix.

**Comment by clausherther** [comment]
@tcwou fyi, cut a new release, should be on the dbt hub site shortly
