### ISSUE TITLE
DBT hub instructs/links to version 0.1.2

### ISSUE THREAD

**Issue by ttusing** [calogica/dbt-expectations#187]
DBT hub instructs people to install version 0.1.2 and links to the readme for 0.1.2. Users landing on dbt-expectations via Google and click on the Github link will see the outdated readme.

https://hub.getdbt.com/calogica/dbt_expectations/0.1.2/

This bit me as I did not realize I was looking at an old readme and the arguments for macros had changed, spent ~45 min debugging and scratching my head.

This also probably explains why on the DBT slack lots of people are using or mention version 0.1.2 during debugging. Example: https://getdbt.slack.com/archives/C2JRTGLLS/p1649122057115889?thread_ts=1648837415.237699&cid=C2JRTGLLS

**Comment by ttusing** [comment]
Looking closer, this might be Google's fault. it looks like it is returning the page for `0.1.2` on dbt hub when I google `dbt_expectations`. Guessing it is happening for a lot of other people too?

Maybe oldest versions could be retired and forward to the current version on DBT hub to get pagerank to fix?

**Comment by clausherther** [comment]
Hi @ttusing , thanks for raising this issue! I think this is indeed a Google issue. Let me see what we can do there. The hub page does link to the latest version.

**Comment by clausherther** [comment]
Looks like there's an open [issue](https://github.com/dbt-labs/hub.getdbt.com/issues/1754) in dbt-labs
