### ISSUE TITLE
Some macros still uses dbt_utils instead of dbt_core

### ISSUE THREAD

**Issue by Karol-Dluzniewski** [calogica/dbt-expectations#195]
Unfortunately some tests still raises warnings about macros being deprecated from dbt_utils in favor of dbt_core.

integration tests shows this as Warning but with non-warning level.
https://app.circleci.com/pipelines/github/calogica/dbt-expectations/81/workflows/2c35d751-e66e-4ddd-a82a-a67033a7412e/jobs/60/parallel-runs/0/steps/0-107

Same errors occurs on my project

**Comment by clausherther** [comment]
Hi @Karol-Dluzniewski  - those deprecation warnings are only during the parsing phase and it's b/c dbt-utils didn't wrap the deprecation code with an `if execute`. They go away on a subsequent run.
Re: the warning, that's unrelated and you can ignore. It has to do with the flakiness of the random data generated for the test.

**Comment by clausherther** [comment]
(fyi, re: the deprecation warnings: https://getdbt.slack.com/archives/CU4MRJ7QB/p1661781392884549?thread_ts=1661487856.978139&cid=CU4MRJ7QB)
