### ISSUE TITLE
Getting warnings in dbt

### ISSUE THREAD

**Issue by pratikpchavan** [calogica/dbt-expectations#215]
Seeing this warning
Warning: the `type_string` macro is now provided in dbt Core. It is no longer available in dbt_utils and backwards compatibility will be removed in a future version of the package. Use `type_string` (no prefix) instead. The dw_dbt.dbt_expectations_expect_column_values_to_be_in_set_stg_amortization_schedules_charged_off_reason__charged_off_reason_is_not_null__deceased__90_days_past_due__debt_settlement_breached__ID_theft__120_days_past_due__debt_settlement__bankruptcy__vehicle_repossessed_and_sold model triggered this warning.
when running source freshness. We only have the dbt_expectations package installed
packages:
      - package: calogica/dbt_expectations
       version: 0.7.0
which references dbt_date and dbt_utils. The cause of the problem seems to be the type_string call in [https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/column_values_basic/expect_column_values_to_be_in_set.sql](https://urldefense.com/v3/__https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/column_values_basic/expect_column_values_to_be_in_set.sql__;!!NsupD1d6!QknLvEjeOVeoERHekSjDWHttb7ebzaZXInHAFg6_9u4v_HIRFRLIX3y3NyyuVdwSmRpBZ_l6rHFxT2IMosqH-P8RC30QyA$)

**Comment by clausherther** [comment]
Hi @pratikpchavan! This is unfortunately out of our control and a bug in the current version of `dbt-utils`, please see this [Slack thread](https://getdbt.slack.com/archives/CU4MRJ7QB/p1664896617281349?thread_ts=1663582277.414579&cid=CU4MRJ7QB).
These warnings do not affect the tests running, and they will go away as soon as that's patched in `dbt-utils`.

**Comment by pratikchavandev** [comment]
@clausherther https://github.com/dbt-labs/dbt-utils/pull/723
