### ISSUE TITLE
expect_column_values_to_be_of_type returns "character varying (16777216) for text data types

### ISSUE THREAD

**Issue by ChristianKohlberg** [calogica/dbt-expectations#22]
SnowflakeColumn(column='ENTITY', dtype='VARCHAR', char_size=16777216, numeric_precision=None, numeric_scale=None)

column.dtype returns "VARCHAR"
column.data_type returns "character varying(16777216)" 

implementation could be changed to use .dtype instead of .data_type like so:
```
{%- macro test_expect_column_values_to_be_of_type(model, column_name, column_type) -%}
{%- if execute -%}

    {%- set column_name = column_name | upper -%}
    {%- set columns_in_relation = adapter.get_columns_in_relation(model) -%}
    {%- set column_type = column_type| upper -%}

    {%- set matching_column_types = [] -%}

    {%- for column in columns_in_relation -%}
        {%- if ((column.name | upper ) == column_name) and ((**column.dtype** | upper ) == column_type) -%}
            {%- do matching_column_types.append(column.name) -%}
        {%- endif -%}
    {%- endfor -%}
    select 1 - {{ matching_column_types | length }}

{%- endif -%}
{%- endmacro -%}

```

**Comment by clausherther** [comment]
Hi @ChristianKohlberg, thanks for filing the issue! That's really interesting. Are you on dbt 0.19? According to the [docs](https://docs.getdbt.com/reference/dbt-classes#properties), `data_type` _should_ be the correct property but I see in the code 0.19 that they reference `dtype`. Let me ask on the Slack channel before going down this route, but I agree that's not great if `data_type` returns the long string.

**Comment by clausherther** [comment]
FYI, looks like there's a bug in how it deals with BQ data types, which led me down the wrong path https://getdbt.slack.com/archives/C2JRRQDTL/p1614872428424400

**Comment by ChristianKohlberg** [comment]
tests executed against dbt v0.18.1.

within dbt the code hasnt changed between 0.17.X until 0.19.X, see [here](https://github.com/fishtown-analytics/dbt/blob/51ccbab1e2ca83c2c02740847ab2057b1cc033bb/core/dbt/adapters/base/column.py#L42): 

dtype looke more like what we are after, if we want to be more abstract, while we should use data_type if we want to be more specific. 

```
    @property
    def data_type(self) -> str:
        if self.is_string():
            return Column.string_type(self.string_size())
        elif self.is_numeric():
            return Column.numeric_type(self.dtype, self.numeric_precision,
                                       self.numeric_scale)
        else:
            return self.dtype
```

**Comment by clausherther** [comment]
Makes sense. Just confirmed that it's ok to use `dtype` even if it's not in the official API.

It'll take a bit to also fix the integration tests for Snowflake, but should have something by the weekend.

**Comment by clausherther** [comment]
@RobbertDM feel free to update the docs before I have a chance too. I'd rather not add a duplicate method though at the moment.
