### ISSUE TITLE
`expect_column_values_to_match_regex` test doesn't work with `dbt-databricks` adapter

### ISSUE THREAD

**Issue by followingell** [calogica/dbt-expectations#228]
**Context:**
- dbt_version: `1.3.0`.
- dbt_databricks_version: `1.3.1`.
- databricks_sql_connector_version: `2.1.0`.

**Behavior:**
_I'm not sure if `dbt-expectations` supports `dbt-databricks`(?), however if so:_

Using [`expect_column_values_to_match_regex`](https://github.com/calogica/dbt-expectations#expect_column_values_to_match_regex) with the [`dbt-databricks`](https://github.com/databricks/dbt-databricks) adapter I am greeted with the following error:
```
21:34:21  Runtime Error in test dbt_expectations_source_expect_column_values_to_match_regex_ ...
21:34:21    Invalid number of arguments for function regexp_instr. Expected: one of 2 and 3; Found: 4; line 21 pos 0
```

I believe this is because Databricks' [`regexp_instr( str, regexp )`](https://docs.databricks.com/sql/language-manual/functions/regexp_instr.html#syntax) function takes only 2 argyuments but is passed 3 in  [`expect_column_values_to_match_regex`]( https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/string_matching/expect_column_values_to_match_regex.sql#L8).

If this needs reporting elsewhere please let me know. Thank you!

**Comment by clausherther** [comment]
Hi @followingell, thanks for the issue. However, we don't support spark or databricks at the moment, because we don't have a CI testing environment for it. 
You might want to see if Joe Markiewicz submits a PR for this to the sparks-utils repo, see https://github.com/calogica/dbt-expectations/pull/226 .

**Comment by followingell** [comment]
_@clausherther Thanks for the clarification and links, I'll check there!_
