### ISSUE TITLE
Wrong Description of Default Behaviour

### ISSUE THREAD

**Issue by praveen-prashant** [calogica/dbt-expectations#229]
In the `REAMDE.md` it says that `quote_values` is `false` by default for `expect_column_distinct_values_to_contain_set`. However, that is not true. It is `true` in the code
<img width="902" alt="image" src="https://user-images.githubusercontent.com/13720799/208601932-6340b635-cfaa-4057-9ede-b5bf7742ca97.png">

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/13720799/208601992-c8cf7755-4523-4f3b-90cb-54899b74521a.png">

https://github.com/calogica/dbt-expectations#expect_column_distinct_values_to_contain_set

https://github.com/calogica/dbt-expectations/blob/main/macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_contain_set.sql

**Comment by clausherther** [comment]
Good catch, thanks.
