### ISSUE TITLE
[Feature Request] support Databricks

### ISSUE THREAD

**Issue by frankivo** [calogica/dbt-expectations#244]
**Is your feature request related to a problem? Please describe.**
Most test, but not all, work with Databricks. For example: expect_column_values_to_match_regex

**Describe the solution you'd like**
A valid implementation for those missing tests.

**Describe alternatives you've considered**
I'm writing custom tests for now.

**Additional context**
Willing to do some coding myself :)

**Comment by clausherther** [comment]
Hi @frankivo - we don't have a way to test against databricks - or any platform other than Postgres, BigQuery or Snowflake - in our CI pipeline, so we don't currently support platforms outside of that core set. 
However, as I've outlined in the [answer to this question](https://github.com/calogica/dbt-expectations/issues/243#issuecomment-1441217671) you can add support for other platforms via shims in their respective **-utils package, such as `spark-utils`. Hope that helps!

**Comment by frankivo** [comment]
Would you take pull requests on macros?

For example:
```
{% macro databricks__regexp_instr(source_value, regexp, position, occurrence, is_raw) %}
regexp_instr( {{ source_value }}, "{{ regexp }}")
{% endmacro %}

```

**Comment by frankivo** [comment]
I'll try :)
https://github.com/databricks/dbt-databricks/pull/280

**Comment by clausherther** [comment]
@frankivo I wonder if they'll want you to implement this in spark-utils though, not in the adapater repo?

**Comment by frankivo** [comment]
Afaik I'm using a databricks feature and not a spark feature. We'll see.

**Comment by clausherther** [comment]
I don't _think_ there is a `databricks-utils` package though, so spark-utils seems to be where the databricks/sparks macros go. My guess would be the macros in the adapter mirror what dbt-core supports, and since they don't have a regexp implementation, the databricks adapter shouldn't either.
