### ISSUE TITLE
[Feature Request] Allow regex flags/parameters in regexp_instr and calling tests

### ISSUE THREAD

**Issue by tconbeer** [calogica/dbt-expectations#245]
**Is your feature request related to a problem? Please describe.**
I would like the regex I provide to `expect_column_values_to_match_regex_list` and similar tests to be case-insensitive, but currently that is not possible.

[Postgres](https://www.postgresql.org/docs/current/functions-matching.html), [Snowflake](https://docs.snowflake.com/en/sql-reference/functions/regexp_instr), and [Redshift](https://docs.aws.amazon.com/redshift/latest/dg/REGEXP_INSTR.html) support an argument (called `flags` in pg and `parameters` in the others) for this. [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_instr) does not, but the column could be lowercased before being passed into regexp_instr.

**Describe the solution you'd like**
Add a `flags` argument to `expect_column_values_to_match_regex_list` and other regex-based tests that accepts a string value and passes it through to the underlying database implementation.

**Describe alternatives you've considered**
Rolling my own test.

**Additional context**
I'm happy to contribute this if there is interest.

**Comment by clausherther** [comment]
@tconbeer Thanks for this feature request! This seems like a useful and worthwhile addition, happy to take any PRs.
