### ISSUE TITLE
[Feature Request]Add support for regex flags for BigQuery

### ISSUE THREAD

**Issue by lookslikeitsnot** [calogica/dbt-expectations#252]
**Is your feature request related to a problem? Please describe.**
For consistency sake since we already support flags for Postgres and Snowflake; and since the project description states it supports BigQuery, I believe it makes sense to add support for re2 flags in BigQuery regex matches .

**Describe the solution you'd like**
Although BigQuery doesn't support flags as regex function parameters, it [uses re2](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_contains) and [re2 supports flags](https://github.com/google/re2/wiki/Syntax) by in-lining the flags (prepending the regex with `(?flag)`). 

**Additional context**
This is a follow-up on issue #245 that added support for flags in Postgres, Snowflake, and Redshift. The idea was briefly introduced [here](https://github.com/calogica/dbt-expectations/pull/250#issuecomment-1484678785)

**Comment by lookslikeitsnot** [comment]
Having flags as parameters for BigQuery instead of having them in the test pattern has a few advantages such as
1. Easier flag validation
2. Simpler adapter switching

However, it adds a few lines of code so it's going to be more work to maintain.

_Note_ In the PR, adding flags both as parameters and in the test pattern doesn't cause execution errors. The flags in the pattern take precedence over the ones in the flag (which is expected flag behavior).
e.g.: 
regex: `(?i)[A-Z]` (case-insensitive letter match)
flags: ` -i` (case-sensitive match)
will be translated to  `(?-i)(?i)[A-Z]` and match any  lower- or upper-case character.

**Comment by clausherther** [comment]
Closed via #253
