### ISSUE TITLE
[Feature Request] Add count to expect_compound_columns_to_be_unique

### ISSUE THREAD

**Issue by VDFaller** [calogica/dbt-expectations#257]
**Is your feature request related to a problem? Please describe.**
Not really a problem. Just a nice to have and it mirrors features in the analogous test in dbt core. 

**Describe the solution you'd like**
Just add a count [probably here](https://github.com/calogica/dbt-expectations/blob/b28ee9bded806543ab2db3d41742f01978eacc09/macros/schema_tests/multi-column/expect_compound_columns_to_be_unique.sql#L42) called `n_records` . Just to match [dbt-core unique test](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/generic_test_sql/unique.sql#LL5C17-L5C26)

I'm happy to put in the MR if y'all think this is a reasonable thing.

**Comment by clausherther** [comment]
Sounds like a good idea to me. Thanks!
