### ISSUE TITLE
[BUG] I cant add severity: WARN 

### ISSUE THREAD

**Issue by YevgenyLevi** [calogica/dbt-expectations#264]
### Is this a new bug in dbt-expectations?

- [ ] I believe this is a new bug in dbt-expectations
- [ ] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior
My code:

tests:
  - dbt_expectations.expect_column_values_to_be_between:
      min_value: 300
      max_value: 850
      severity: WARN
### Expected Behavior
Add severity WARN
### Relevant log output
test definition dictionary must have exactly one key, got [('dbt_expectations.expect_column_values_to_be_between', {'min_value': 300, 'max_value': 850}), ('severity', 'WARN')] instead (2 keys)
### Environment
TEST
```markdown
- OS:
- Python:
- dbt:
- dbt-expectations:
```

### Which database adapter are you using with dbt?
Postgres

Note: dbt-expectations currently does not support database adapters other than the ones listed below.

- Postgres
- Snowflake
- BigQuery

**Comment by clausherther** [comment]
Hi, this is actually not an issue with `severity`, you need indent the all keys:
```yaml
- dbt_expectations.expect_column_values_to_be_between:
    min_value: 300
    max_value: 850
    severity: WARN
```
See [this](https://github.com/calogica/dbt-expectations/blob/6700bbc09aed5613b15ac98524b2c618b4b153ba/integration_tests/models/schema_tests/schema.yml#L266) example.

**Comment by YevgenyLevi** [comment]
Yes, actually now I see that it works, I don't know what I changed in my indentation, looks the same :) 
thanks!
