### ISSUE TITLE
[Feature Request] Clarify tolerance percentage format

### ISSUE THREAD

**Issue by mbkupfer** [calogica/dbt-expectations#265]
**Is your feature request related to a problem? Please describe.**
Clarify that percentage tolerance should be expressed as a decimal value as it could be misinterpreted to be a nominal value and cause silent errors.

**Describe the solution you'd like**
Simple addition to readme. I actually already have something ready to go here: https://github.com/mbkupfer/dbt-expectations/commit/e4735566d701b41fffb0c02cc690033bf29c4a56, but realized I needed to first open an issue the pull request.

**Describe alternatives you've considered**
n/a

**Additional context**
Backstory, I made the mistake of assuming it was nominal and was thinking I was testing a 0.5% tolerance when in fact it was looking at a 50% tolerance! Needless to say, I should have read the source code beforehand, but I'm sure it would be more accessible if we can just add a few extra words in the readme :)

**Comment by clausherther** [comment]
Sounds good to me, thanks
