### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by welsh-wonder** [calogica/dbt-expectations#270]
**Is your feature request related to a problem? Tests for duplicates for example work great, but you don't know where or what business key the duplicate is on. Rather than just testing the existence it would be great to show end users what records are considered to be duplicate to help aid remediation at source. 

**Describe the solution you'd like**

Show duplicate count, with business key. 

**Describe alternatives you've considered**
 
Changing the compiled SQL, but it is a bit onerous

**Additional context**
N/A

**Comment by clausherther** [comment]
Hi @welsh-wonder - I'm a little unclear what this feature request is actually requesting. Could you please add a little more specifics re: what you would expect the output to show etc?
Also, we're just using the underlying dbt testing framework for these macros, so any output is ultimately controlled by what dbt supports.
