### ISSUE TITLE
[BUG] restrictive dbt_date pin

### ISSUE THREAD

**Issue by RoyalTS** [calogica/dbt-expectations#275]
### Is this a new bug in dbt-expectations?

- [ ] I believe this is a new bug in dbt-expectations
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`dbt_date` is [currently pinned to a now outdated version of `dbt_date`](https://github.com/calogica/dbt-expectations/blob/f22c7e3ba1a3cda1bfd476de40e27e390e38d9a5/packages.yml#L3)

Is this necessary, or could this be relaxed?

**Comment by clausherther** [comment]
Hi, that's intentional. dbt-date 0.9.* only adds support for Spark, which dbt-expectations currently does not have. The next release of dbt-expectations may support Spark, at which point it'll package the latest version of dbt-date.
