### ISSUE TITLE
No boolean support in SQL Server

### ISSUE THREAD

**Issue by b-per** [calogica/dbt-expectations#28]
Hi!

I tried to run `dbt-expectations` on my Azure SQL DB, and while some tests are working out of the box, other ones are raising SQL errors.

One of them is due to the macro `expression_is_true.sql`. The current macro performs a logic test in `{{expression}}` in the `select` statement but this is not valid in SQL Server. My current workaround is to change the default `test_condition="= true"` to `test_condition="= 1"` and use a `case when` statement in the select.

```
with grouped_expression as (

    select
        {% if group_by_columns %}
        {% for group_by_column in group_by_columns -%}
        {{ group_by_column }} as col_{{ loop.index }},
        {% endfor -%}
        {% endif %}
        case when {{ expression }} then 1 else 0 end as expression
    from {{ model }}
     {%- if row_condition %}
    where
        {{ row_condition }}
    {% endif %}
    {% if group_by_columns %}
    group by
    {% for group_by_column in group_by_columns -%}
        {{ group_by_column }}{% if not loop.last %},{% endif %}
    {% endfor %}
    {% endif %}
```

I've not done extensive testing but this seems to work with the few tests I've done so far. 
Would it make sense to change the macro for all the SQL engines or put in place conditions for SQL Server vs the rest?

**Comment by clausherther** [comment]
Hi @camfrout! Thanks for raising this issue, very interesting to hear that SQL Server doesn't support booleans. I don't have ~~a lot of~~ any experience with Azure SQL, but I'd be happy to accept a PR from you if you're interest in adding and testing that?
For example, I could see refactoring the `expression_is_true` macro into an adapter macro with a special case for Azure. Happy to help with the syntax on that if you'd like to get it going and do the integration testing?

**Comment by b-per** [comment]
Thanks! I'll give a go at the adapter and will let you know if I have questions on the syntax then.

**Comment by b-per** [comment]
It actually took some work to get the integration tests running on SQL Server. I will keep this issue opened for now but I will most likely suggest a few PRs in `dbt-date` and in this repo, targeting the integration tests before tackling the first issue.

The good news is that in my first tests the dispatcher to target SQL Server is working just fine.

**Comment by b-per** [comment]
Hi @clausherther.

With this repo, would your suggestion be to keep it for Snowflake, BigQuery and Redshift/Postgres like `dbt-date` and create other DB specific versions in different repos?

**Comment by clausherther** [comment]
@b-per yes, that was my longer term plan. We sort of support Spark right now, but I think it would also make sense to break out non-core support into a sub package.

**Comment by b-per** [comment]
Initial support for T-SQL is now available through an adapter package: https://github.com/b-per/dbt-expectations-tsql
