### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by asterixas** [calogica/dbt-expectations#283]
Hello everyone, it is sad but dbt-expectation package does not work with dbt-trino adapater, at least for me. is there anyone who tried to do the data quality tests with dbt-trino and dbt-expectations? Could you please implement that important feature for dbt-trino

**Comment by clausherther** [comment]
Hi, we don't have a way to set up automated testing during CI for trino, so we will not be supporting trino at the moment.

**Comment by damian3031** [comment]
Trino is supported since https://github.com/calogica/dbt-expectations/releases/tag/0.10.3.
