### ISSUE TITLE
[Feature Request] Update the package version for dbt-utils

### ISSUE THREAD

**Issue by sfc-gh-kumaurya** [calogica/dbt-expectations#284]
**Is your feature request related to a problem? Please describe.**
dbt-utils package version is not up to date.

**Describe the solution you'd like**
dbt-utils package version should be updated to
```packages:
  - package: calogica/dbt_date
    version: [">=0.9.0", "<0.10.0"]
```

**Comment by sfc-gh-kumaurya** [comment]
@clausherther I think you are the right person here. Could you pls look into this?

**Comment by clausherther** [comment]
1) we don't use dbt-utils, you mean dbt-date
2) See https://github.com/calogica/dbt-expectations/issues/277 and https://github.com/calogica/dbt-expectations/issues/275 for prior answers.

**Comment by sfc-gh-kumaurya** [comment]
> 1. we don't use dbt-utils, you mean dbt-date
> 2. See [Update calogica/dbt_date version. #277](https://github.com/calogica/dbt-expectations/issues/277) and [[BUG] restrictive dbt_date pin #275](https://github.com/calogica/dbt-expectations/issues/275) for prior answers.

yeah sorry, I do mean dbt-date. Thanks for the reference @clausherther, I'll wait for the update.
