### ISSUE TITLE
[Feature Request] ClickHouse support in tests using lag function

### ISSUE THREAD

**Issue by zstipanicev** [calogica/dbt-expectations#324]
**Is your feature request related to a problem? Please describe.**
ClickHouse doesn't have the standard _lag_ function, instead it has _lagInFrame_ function so tests using _lag_ fail

**Describe the solution you'd like**
I have already implemented the suggested workaround from the ClickHouse [docs](https://clickhouse.com/docs/en/sql-reference/window-functions#:~:text=lag/lead(value%2C%20offset)) and would like to push it into the main repo so that others can use it as well

**Describe alternatives you've considered**
Implementing the solution

**Additional context**
n/a

**Comment by clausherther** [comment]
We currently do not support ClickHouse since we do not have CI in place for testing.
