### ISSUE TITLE
macro test_expect_column_distinct_values_to_be_in_set returns false positive

### ISSUE THREAD

**Issue by Pegspeterson** [calogica/dbt-expectations#33]
I think that the final where clause in macro test_expect_column_distinct_values_to_be_in_set 
should be
      where
          **_s_**.value_field is null

not 
      where
          **_v_**.value_field is null

**Comment by clausherther** [comment]
Good eye @Pegspeterson, thanks for raising that issue. You're right, [this line](https://github.com/calogica/dbt-expectations/blob/7d52fd5615592603c1f7c0e6e4f30188a5e9c7d9/macros/schema_tests/aggregate_functions/expect_column_distinct_values_to_be_in_set.sql#L47) is wrong, will get that fixed!

**Comment by Pegspeterson** [comment]
Thank you for the quick fix!  I was able to validate and it now fails as expected.
