### ISSUE TITLE
Update expectations to at least pass integrations tests for dbt==0.20.0-b1

### ISSUE THREAD

**Issue by clausherther** [calogica/dbt-expectations#59]
We need to rewrite expectations to return failing rows, not counts

**Comment by jtcohen6** [comment]
We just released 0.20.0rc1, and it includes a new config, [`fail_calc`](https://next.docs.getdbt.com/reference/resource-configs/fail_calc), that makes it possible to use calculations other than `count(*)` against failing rows. I think this will be important for backwards consistency with test queries that previously returned other numbers.

I took a look at #61, I can leave a few comments.
