### ISSUE TITLE
get_select() TSQL compatibility

### ISSUE THREAD

**Issue by swanderz** [calogica/dbt-expectations#62]
as part the work in https://github.com/dbt-msft/tsql-utils/pull/44 to make this package compatible with the dbt-msft adapters, I'm stuck trying to shim the first macro

how can I make this query TSQL- and dbt-expectations-compatible? I'm struggling to grok the intent behind `dbt-expectations.test_equal_expression()`'s default argument of `groupby=['col']`.

[Here's a long write up](https://gist.github.com/swanderz/dd76c06622335260ccea690b70b207d4) of the steps I went through to discover that `get_select()` was the problematic macro.

Very much appreciate the work you've done here, we'd like to re-use your integration tests as much as possible

### failed compilation syntax
```sql
select
    'col' as col_1,
    sum(col_numeric_a) as expression
from
    "dbt-msft-serverless-db"."integration_tests_azsql_dbt_expectations_integration_tests"."data_test"
group by
    'col'
```

### generic example
here's a generic example that I don't understand how this works on Snowflake or BigQuery right now because it doesn't work on Postgres or TSQL

```sql
WITH CTE AS (
    SELECT 1 as col_numeric_a
    UNION 
    SELECT 2 as col_numeric_a
)
SELECT
    'col' AS col_1,
    sum(col_numeric_a) AS expression
FROM CTE
GROUP BY 'col'
```

**Comment by b-per** [comment]
In T-SQL `a cross join b` should work fine, yes
