### ISSUE TITLE
expect_column_values_to_be_in_set not including nulls

### ISSUE THREAD

**Issue by domfp13** [calogica/dbt-expectations#87]
Hi folks, 

I am using the following test: expect_column_values_to_be_in_set

when I included null inside of the value_set it keeps throwing out errors, I am working with Redshift

**Comment by clausherther** [comment]
Hi @domfp13, thanks for creating that issue! Would you mind posting the error and as well your test config with the value_set parameter? I don't have a Redshift instance to test against, but hopefully I can reproduce it in Postgres.

**Comment by clausherther** [comment]
See: https://getdbt.slack.com/archives/CBSQTAPLG/p1625071167398000?thread_ts=1625069726.397100&cid=CBSQTAPLG

> one thing you can try on expect_column_values_to_be_in_set is to set row_condition to row_condition: "renewal_type is not null" which excludes those rows from the test, then you can ignore null in your value_set.

**Comment by clausherther** [comment]
Basically, if you include `<null>` in `value_set`, it's interpreted as a string, `"<null>"` which will fail in your case.

**Comment by domfp13** [comment]
This does not work also 
![image](https://user-images.githubusercontent.com/7782876/124008453-b7865a00-d9dc-11eb-80c5-c1883664353b.png)

**Comment by clausherther** [comment]
@domfp13 correct, `NULL` won't work for the same reason, it'll be converted to a string and since your column probably does't contains `"NULL"` the test will fail.
Have you tried what I suggested earlier?
```
row_condition: "renewal_type is not null"
```

**Comment by domfp13** [comment]
Worked like a charm! Thanks!!!!!! 🙏

**Comment by SuperbTUM** [comment]
I got an implementation to let the macro work like this. Basically if null is in the value set, we can say 
```
select * from xxx minus select null;
```

> This does not work also ![image](https://user-images.githubusercontent.com/7782876/124008453-b7865a00-d9dc-11eb-80c5-c1883664353b.png)
