### ISSUE TITLE
Alternatives to re-implementation?

### ISSUE THREAD

**Issue by abegong** [calogica/dbt-expectations#9]
Hi @clausherther ! 

I'm one of the maintainers of Great Expectations. I'm excited that you're working on bringing dbt and GE functionality together. Lots of teams use both tools, and we're very supportive of even closer collaboration.

Looking at your implementation, I can see several places where we can probably save you some work, but the right way to implement will depend on exactly what you're trying to accomplish. We'd be happy to have someone on the GE team collaborate to help.

Are you up for a call to discuss?

**Comment by clausherther** [comment]
Hi @abegong, that sounds great! This mostly started as a spike to see if I can SQL puzzle my way though this, and also as an effort to have a comprehensive reusable dbt test package. Happy to chat about where to take this! I'm at claus@calogica.com if we want to set something up next week. Thanks!

**Comment by abegong** [comment]
Awesome, I'll ping you in just a moment.

**Comment by misteliy** [comment]
The problem with current state is that you GE is not part of the dbt execution. Hence, a dbt package makes a lot of sense to me.

**Comment by clausherther** [comment]
Just to close this out: Abe, Tal, Sam and I met today to chat. While I (and others!) will maintain this dbt/SQL-based version for those use cases where Python isn't an option (current dbt Cloud etc), we will work with the GE team to stay in sync on API changes and especially test cases and test datasets. More to come. 

Thanks!
