### ISSUE TITLE
Update readme for the test "expect_table_column_count_to_be_between"

### ISSUE THREAD

**Issue by s-vinay** [calogica/dbt-expectations#95]
Attachment:
![dbt_expectation issues](https://user-images.githubusercontent.com/83854194/126361021-c739dd7b-c940-4a21-bbbc-f714d09655cd.png)

Issue description:
The readme says that the test "expect_table_column_count_to_be_between" is applied to column but it should be Model, Source and Seeds as this is the test for count of columns in the whole object.

**Comment by clausherther** [comment]
Closed via #96
