### ISSUE TITLE
Regex expectations broken on Redshift

### ISSUE THREAD

**Issue by mirosval** [calogica/dbt-expectations#97]
Hello, I've upgraded to dbt `0.20.0` and dbt-expectations `0.4`. After that I started seeing the following error:

```Invalid operation: function regexp_matches(character varying, "unknown") does not exist```

My understanding of what happened is that this https://github.com/calogica/dbt-expectations/issues/39 was fixed, which replaced the `regexp_instr` with `regex_matches` on Postgres. However because Redshift falls back to Postgress version of the macro under the new dispatch rules, this is also `regex_matches` is invoked on Redshift. But redshift does not have that function (even though it does have the original regexp_instr): https://docs.aws.amazon.com/redshift/latest/dg/REGEXP_INSTR.html

**Comment by clausherther** [comment]
Interesting, so I had thought that Redshift would use the `default_` implementation, which [matches](https://github.com/calogica/dbt-expectations/blob/ad9767114ff4159fdaafe00064525ce2b50ef743/macros/regex/regexp_instr.sql#L10) the Redshift function. But you're saying dbt uses the Postgres version in this case? Like `Redshift > Postrges > Default`?

**Comment by mirosval** [comment]
> Plugin maintainers: For adapters that inherit from other adapters (e.g. dbt-postgres → dbt-redshift), adapter.dispatch() will now include parent macro implementations as viable candidates (#2923, #3296)

This is from https://github.com/dbt-labs/dbt/releases/tag/v0.20.0 so I think this is what is happening here and why Redshift doesn't use the default.

**Comment by mirosval** [comment]
I've simply added this locally to `dbt_expectations/macros/regex/regexp_instr.sql`:

```jinja
{% macro redshift__regexp_instr(source_value, regexp, position, occurrence) %}
regexp_instr({{ source_value }}, '{{ regexp }}', {{ position }}, {{ occurrence }})
{% endmacro %}
```
(its just duplicated and renamed the `default` adapter to `redshift`) and it seems to work. I can make a PR if you like
